#!/bin/bash

# Setup open alias
if [[ "$OSTYPE" == darwin* ]]; then
  alias o='open'
  alias grep='ggrep'
  alias ls='ls -G'
else
  alias o='xdg-open'
  alias ls='ls --color'
  # alias xclip to pbcopy and paste
  if [ $+commands[xclip] ]; then
    alias pbcopy='xclip -selection clipboard -in'
    alias pbpaste='xclip -selection clipboard -out'
  fi
fi

alias pbc='pbcopy'
alias pbp='pbpaste'

# Add get aliase for downloading with progress
if [ $+commands[curl] ]; then
  alias get='curl --continue-at - --location --progress-bar --remote-name --remote-time'
elif [ $+commands[wget] ]; then
  alias get='wget --continue --progress=bar --timestamping'
fi

# Serve PWD over http
if [ $+commands[python3] ]; then
  alias http-serve='python3 -m http.server'
else
  alias http-serve='python -m SimpleHTTPServer'
fi

alias grep='grep --color=auto --exclude-dir={.bzr,CVS,.git,.hg,.svn}'

alias diffdir='diff -rq'

# Alias NeoVim for Vim
if [ $+commands[nvim] ]; then
  alias vim='nvim'
fi
alias v='vim'


# Slightly over the top set of functions for defining aliases
function def_real_alias () {
  while [[ $# -ge 2 ]]; do
    alias "$1=$2"
    shift 2
  done
}

function def_real_aliases () {
  def_real_alias $real_aliases
  unset real_aliases
}

function def_global_alias () {
  while [[ $# -ge 2 ]]; do
    alias -g "$1=$2"
    shift 2
  done
}

function def_global_aliases () {
  def_global_alias $global_aliases
  unset global_aliases
}

function def_fun () {
  while [[ $# -ge 2 ]]; do
    eval "function $1 () { $2 \$@ }"
    shift 2
  done
}

function def_funs () {
  def_fun $funs
  unset funs
}

# ssh and open port
ssp(){
    ssh -L "$1"\:localhost\:"$1" "$2"
}

newMAC(){
    ifconfig en0 | grep ether
    MAC=$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//')
    # echo MAC="$MAC"
    sudo ifconfig en0 ether "$MAC"
    sudo ifconfig en0 down && sudo ifconfig en0 up
    ifconfig en0 | grep ether
}

real_aliases=(
    inet "ifconfig | grep 'inet '"
    inet6 "ifconfig | grep 'inet6 '"
    o "open ."
    wanip "dig @resolver1.opendns.com ANY myip.opendns.com +short"
    bat "bat --theme=\"Monokai Extended Origin\" --color=always"
    dots "cd $ZDOTDIR/.."
    gs "git status"
); def_real_aliases


funs=(
    c "clear"
    nsl "nslookup"
    l "ls -FAtrl"
    la "ls -FAl"
    l1 "l -1"
    lh "l -H"
    lr "l -R"
    lk "la -l"
); def_funs

# grep for a given process and optionally cut the length of the output while also hiding any grep process
psaux(){
    ps aux | grep "$1" | grep -v "grep"| cut -c 1-"$2"
}

