[options]
    lint_engine = 'ale'

    colorscheme = 'onedark'
    colorscheme_bg = 'dark'

    guifont = 'JetBrainsMono\ Nerd\ Font\ Mono:h15'
    enable_guicolors = true

    windows_smartclose = 'Z'

    statusline_separator = 'arrow'
    statusline_iseparator = 'arrow'
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true 

    bootstrap_before = 'bootstrap#before'
    bootstrap_after = 'bootstrap#after'
    automatic_update = true
    filemanager = 'nerdtree'
    filetree_direction = 'left'


[[layers]]
    name = 'shell'
    default_position = 'bottom'
    default_height = 30

[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = 'complete'
    auto_completion_tab_key_behavior = 'smart'

[[layers]]
    name = 'colorscheme'
[[layers]]
    name = 'fzf'
[[layers]]
    name = 'git'
    git_plugin = 'fugitive'
[[layers]]
    name = 'VersionControl'
[[layers]]
    name = 'sudo'
[[layers]]
    name = 'tools'
[[layers]]
    name = 'ui'

[[layers]]
  name = 'checkers'
  lint_on_the_fly = true
  lint_on_save = true
  show_cursor_error = true
  lint_engine = 'ale'

[[layers]]
  name = "format"
  # format_on_save = true


[[layers]]
  name = "lang#cmake"

[[layers]]
    name = 'lang#sh'

[[layers]]
    name = 'lang#go'

[[custom_plugins]]
    repo = 'mattn/vim-goimports'
    merged = false

[[layers]]
    name = 'lang#groovy'

[[layers]]
    name = 'lang#toml'

[[layers]]
  name = 'lang#markdown'

[[layers]]
    name = 'lang#python'
    enable_typeinfo = true
    python_interpreter = '/usr/bin/python3'

[[layers]]
    name = 'lang#javascript'

[[layers]]
    name = 'lang#typescript'

[[custom_plugins]]
    repo = 'mxw/vim-jsx'
    merged = false

[[custom_plugins]]
    repo = 'tpope/vim-sleuth'
    merged = false

[[custom_plugins]]
    repo = 'nathanaelkane/vim-indent-guides'
    merged = false

[[custom_plugins]]
    repo = 'folke/todo-comments.nvim'
    merged = false

[[custom_plugins]]
    repo = 'Xuyuanp/nerdtree-git-plugin'
    merged = false

[[custom_plugins]]
    repo = 'PhilRunninger/nerdtree-visual-selection'
    merged = false

[[custom_plugins]]
    repo = 'ryanoasis/vim-devicons'
    merged = false

[[custom_plugins]]
    repo = 'sheerun/vim-polyglot'
    merged = false

[[custom_plugins]]
    repo = 'nvim-lua/plenary.nvim'
    merged = false

[[custom_plugins]]
    repo = 'tpope/vim-rhubarb'
    merged = false

[[custom_plugins]]
    repo = 'knubie/vim-kitty-navigator'
    merged = false

[[custom_plugins]]
    repo = 'LhKipp/nvim-nu'
    merged = false
