[options]
    # autocomplete_method = 'coc'
    # snippet_engine = 'ultisnips'
    lint_engine = 'ale'

    colorscheme = 'onedark'
    colorscheme_bg = 'dark'

    guifont = 'JetBrainsMono\ Nerd\ Font\ Mono:h15'
    enable_guicolors = true

    windows_smartclose = 'Z'

    statusline_separator = 'arrow'
    statusline_iseparator = 'arrow'
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true 

    bootstrap_before = 'bootstrap#before'
    bootstrap_after = 'bootstrap#after'
    automatic_update = true
    filemanager = 'nerdtree'
    filetree_direction = 'left'


[[layers]]
    name = 'shell'
    default_position = 'bottom'
    default_height = 30

[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = 'complete'
    auto_completion_tab_key_behavior = 'smart'

[[layers]]
    name = 'colorscheme'
[[layers]]
    name = 'fzf'
[[layers]]
    name = 'git'
    git_plugin = 'fugitive'
[[layers]]
    name = 'VersionControl'
[[layers]]
    name = 'sudo'
[[layers]]
    name = 'tools'
[[layers]]
    name = 'ui'

[[layers]]
  name = 'checkers'
  lint_on_the_fly = true
  lint_on_save = true
  show_cursor_error = true
  lint_engine = 'ale'

[[layers]]
  name = "format"
  # format_on_save = true


[[layers]]
  name = "lang#cmake"

[[layers]]
    name = 'lang#java'
    format_on_save = false
    java_formatter_jar = '/usr/share/java/google-java-format/google-java-format.jar'

[[layers]]
  name = 'lang#haskell'

[[layers]]
    name = 'lang#sh'

[[layers]]
    name = 'lang#go'
[[custom_plugins]]
    repo = 'mattn/vim-goimports'
    merged = false

[[layers]]
    name = 'lang#groovy'

[[layers]]
    name = 'lang#toml'

[[layers]]
  name = 'lang#markdown'
  # enabled_formater = ['prettier']

[[layers]]
    name = 'lang#python'
    enable_typeinfo = true
    python_interpreter = '/usr/bin/python3'

[[layers]]
    name = 'lang#javascript'
    auto_fix = true
    enable_flow_syntax = true
[[layers]]
    name = 'lang#typescript'
[[custom_plugins]]
    repo = 'mxw/vim-jsx'
    merged = false

[[custom_plugins]]
    repo = 'tpope/vim-sleuth'
    merged = false
[[custom_plugins]]
    repo = 'nathanaelkane/vim-indent-guides'
    merged = false
[[custom_plugins]]
    repo = 'folke/todo-comments.nvim'
    merged = false
[[custom_plugins]]
    repo = 'Xuyuanp/nerdtree-git-plugin'
    merged = false
[[custom_plugins]]
    repo = 'PhilRunninger/nerdtree-visual-selection'
    merged = false

[[custom_plugins]]
    repo = 'ryanoasis/vim-devicons'
    merged = false

[[custom_plugins]]
    repo = 'vim-scripts/gitignore'
    merged = false

[[custom_plugins]]
    repo = 'liuchengxu/graphviz.vim'
    merged = false

[[custom_plugins]]
    repo = 'NoahTheDuke/vim-just'
    merged = false

[[custom_plugins]]
    repo = 'hashivim/vim-hashicorp-tools'
    merged = false

[[custom_plugins]]
    repo = 'hashivim/vim-terraform'
    merged = false
[[custom_plugins]]
    repo = 'jvirtanen/vim-hcl'
    merged = false

[[custom_plugins]]
    repo = 'martinda/Jenkinsfile-vim-syntax'
    merged = false

[[custom_plugins]]
    repo = 'cdelledonne/vim-cmake'
    merged = false

[[custom_plugins]]
    repo = 'sheerun/vim-polyglot'
    merged = false

[[custom_plugins]]
    repo = 'ckipp01/nvim-jenkinsfile-linter'
    merged = false

[[custom_plugins]]
    repo = 'nvim-lua/plenary.nvim'
    merged = false

# [[custom_plugins]]
#     repo = 'github/copilot.vim'
#     merged = false
#
# [[custom_plugins]]
#     repo = 'github/copilot.vim'
#     merged = false

[[custom_plugins]]
    repo = 'knubie/vim-kitty-navigator'
    merged = false
