[options]
    autocomplete_method = 'coc'
    snippet_engine = 'ultisnips'

    colorscheme = 'material'
    colorscheme_bg = 'dark'
    enable_guicolors = true

    enable_vimfiler_gitstatus = true
    windows_smartclose = 'Q'

    statusline_separator = 'arrow'
    statusline_iseparator = 'arrow'
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

    bootstrap_before = 'bootstrap#before'
    bootstrap_after = 'bootstrap#after'
    automatic_update = true



[[layers]]
    name = 'shell'
    default_position = 'bottom'
    default_height = 30
[[layers]]
    name = "autocomplete"
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"
[[layers]]
    name = 'colorscheme'
[[layers]]
    name = 'fzf'
[[layers]]
    name = 'git'
[[layers]]
    name = 'sudo'
[[layers]]
    name = 'tools'
[[layers]]
    name = 'ui'
    enable_scrollbar = true

[[layers]]
  name = "checkers"
  lint_engine = "ale"
  lint_on_the_fly = true

[[layers]]
    name = "lsp"
[[layers]]
    name = 'lang#java'
[[layers]]
    name = 'lang#sh'
[[layers]]
    name = 'lang#go'
[[layers]]
    name = 'lang#toml'
[[layers]]
    name = 'lang#latex'
[[layers]]
    name = 'lang#c'
[[layers]]
  name = 'lang#markdown'
  enabled_formater = 'prettier'
[[layers]]
    name = 'lang#python'
    enable_typeinfo = true
[[layers]]
    name = 'lang#javascript'
    auto_fix = true
    enable_flow_syntax = true
[[layers]]
    name = 'lang#typescript'

[[custom_plugins]]
    repo = 'tpope/vim-sleuth'
    merged = false

[[custom_plugins]]
    repo = 'mxw/vim-jsx'
    merged = false

[[custom_plugins]]
    repo = 'nathanaelkane/vim-indent-guides'
    merged = false
