tap "fabianishere/personal"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "mikhailai/misc"
tap "nektos/tap"
tap "homebrew/cask-drivers"
brew "curl"
brew "git"
brew "htop"
brew "jq"
brew "mas"
brew "ncdu"
brew "nmap"
brew "reattach-to-user-namespace"
brew "rename"
brew "shellcheck"
brew "tldr"
brew "tree"
brew "urlview"
brew "watch"
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "fabianishere/personal/pam_reattach"
brew "git-delta"
cask "alacritty"
cask "brave-browser"
cask "android-platform-tools"
cask "insomnia"
cask "jetbrains-toolbox"
cask "monitorcontrol"
cask "spotify"
cask "vagrant"
cask "gitkraken"
cask "onyx"
#cask "mactex"
cask "omnidisksweeper"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "amethyst"
cask "alfred"
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft To Do", id: 1274495053
mas "Pocket", id: 568494494
mas "Slack", id: 803453959
mas "Termius", id: 1176074088
mas "The Unarchiver", id: 425424353
mas "Trello", id: 1278508951
