[tools]
act = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
bun = "latest"
"cargo:procs" = "latest"
ccache = "latest"
claude-code = "latest"
cloudflared = "latest"
cmake = "3.31.7"
conan = "latest"
delta = "latest"
dive = "latest"
fzf = "latest"
gh = "latest"
"github:anomalyco/opencode" = "latest"
go = "latest"
"go:github.com/lucagrulla/cw" = "latest"
"go:github.com/openrdap/rdap/cmd/rdap" = "v0.9.1"
golangci-lint = "latest"
goreleaser = "latest"
granted = "latest"
hexyl = "latest"
httpie-go = "latest"
hugo-extended = "latest"
java = "latest"
jq = "latest"
just = "latest"
jwt = "latest"
mold = "latest"
neovim = "latest"
ninja = "latest"
node = "24"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@openchamber/web" = "latest"
"npm:ccusage" = "latest"
"npm:openportal" = "latest"
"npm:postcss" = "latest"
"npm:release-please" = "latest"
"npm:renovate" = "latest"
"npm:typescript-language-server" = "latest"
oh-my-posh = "latest"
pandoc = "latest"
pipx = "latest"
"pipx:cibuildwheel" = "latest"
"pipx:credstash" = "latest"
"pipx:git-filter-repo" = "latest"
"pipx:httpie" = "latest"
"pipx:keyring" = "latest"
"pipx:maturin" = "latest"
"pipx:nbdime" = "latest"
"pipx:pyiceberg" = "latest"
"pipx:terraform-local" = "latest"
pnpm = "latest"
poetry = "latest"
pre-commit = "latest"
prettier = "latest"
python = ["3.13", "3.12", "3.11", "3.10", "3.14"]
rclone = "latest"
ripgrep = "latest"
ruff = "latest"
rust = "latest"
shellcheck = "latest"
spark = "3.5.6"
sqlite = "latest"
terraform = "latest"
terraform-docs = "latest"
terragrunt = "latest"
tflint = "latest"
tlrc = "latest"
trivy = "latest"
upx = "latest"
usage = "latest"
uv = "latest"
yarn = "latest"
yq = "latest"

[settings]
experimental = false
idiomatic_version_file_enable_tools = ["python"]
