[tools]
act = "latest"
aws-cli = "latest"
ccache = "latest"
cloudflared = "latest"
cmake = "3.31.7"
conan = "2.16.1"
delta = "latest"
dive = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
granted = "latest"
hexyl = "latest"
httpie-go = "latest"
hugo-extended = "latest"
java = "latest"
jq = "latest"
jwt = "latest"
lua = "5.1"
mold = "latest"
neovim = "latest"
node = "20"
"npm:@google/gemini-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:release-please" = "latest"
"npm:typescript-language-server" = "latest"
pandoc = "latest"
pipx = "latest"
"pipx:credstash" = "latest"
"pipx:git-filter-repo" = "latest"
"pipx:httpie" = "latest"
"pipx:maturin" = "latest"
"pipx:nbdime" = "latest"
"pipx:pyiceberg" = "latest"
pnpm = "latest"
poetry = "latest"
postgres = "latest"
pre-commit = "latest"
prettier = "latest"
python = "3.13"
rclone = "latest"
ripgrep = "latest"
ruff = "latest"
rust = "latest"
spark = "3.5.6"
terraform = "latest"
terraform-docs = "latest"
terragrunt = "latest"
tflint = "latest"
tlrc = "latest"
trivy = "latest"
upx = "latest"
usage = "latest"
uv = "latest"
yq = "latest"
[env]
_.file = ".env.yaml"

[settings]
experimental = false
idiomatic_version_file_enable_tools = ["python"]
