#!/usr/bin/env bash

function aws-ecs-exec() {
  if [[ $# -lt 1 ]]; then
      echo "Error: At least one argument is required."
      return
  fi
  cluster="$(aws ecs list-clusters --query clusterArns | jq -c '.[]' -r | awk -F '/' '{print $2}' | fzf)"
  preview="aws ecs describe-tasks --cluster $cluster --tasks {} --query 'tasks[0].taskDefinitionArn' | xargs -ro aws ecs describe-task-definition --query taskDefinition.taskDefinitionArn --output=text --task-definition"
  taskArn="$(aws ecs list-tasks --cluster "$cluster" --query taskArns | jq -c '.[]' -r | fzf --preview="$preview")"
  containerName="$(aws ecs describe-tasks --tasks $taskArn --cluster $cluster --query 'tasks[0].containers[].name' | jq -c '.[]' -r | fzf)"
  aws ecs execute-command \
    --cluster "$cluster" \
    --task "$(echo -n "$taskArn" | awk -F '/' '{print $3}')" \
    --container "$containerName" \
    --interactive \
    --command $1
}
