#!/bin/bash
if [[ "$OSTYPE" != darwin* ]]; then
  alias open='xdg-open'
  # alias xclip to pbcopy and paste
  if [ $+commands[xclip] ]; then
    alias pbcopy='xclip -selection clipboard -in'
    alias pbpaste='xclip -selection clipboard -out'
  fi
fi

function o(){
  nohup bash -c "$(whence open) $@" >/dev/null 2>&1 & disown
}

alias pbc='pbcopy'
alias pbp='pbpaste'
alias gcurl='curl --header "Authorization: Bearer $(gcloud auth print-identity-token)"'


# Add get aliase for downloading with progress
if [ $+commands[curl] ]; then
  alias get='curl --continue-at - --location --progress-bar --remote-name --remote-time'
elif [ $+commands[wget] ]; then
  alias get='wget --continue --progress=bar --timestamping'
fi

# Serve PWD over http
if [ $+commands[python3] ]; then
  alias http-serve='python3 -m http.server'
else
  alias http-serve='python -m SimpleHTTPServer'
fi

alias grep='grep --color=always --exclude-dir={.bzr,CVS,.git,.hg,.svn}'
alias lanip="ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'"

# Alias NeoVim for Vim
if command -v nvim &> /dev/null
then
  alias vim='nvim'
fi

if command -v step-cli &> /dev/null
then
  alias -g step='step-cli'
fi

if type ifconfig >/dev/null ; then
  alias inet='ifconfig | grep "inet "'
  alias inet6='ifconfig | grep "inet6 "'
else
  alias inet='ip addr | grep "inet " | tr -s " " | cut -d " " -f3'
  alias inet6='ip addr | grep "inet6 " | tr -s " " | cut -d " " -f3'
fi
alias wanip='dig @resolver1.opendns.com ANY myip.opendns.com +short'
alias dots='pushd $DOTDIR/'
alias zdots='pushd $ZDOTDIR'
alias gs='git status'
alias lspath='echo "$PATH" | tr ":" "\n"'
alias lsfpath='echo "$fpath" | tr " " "\n"'


alias fce='emoji::emoji_get|pbc'

# alias ls='exa -al --color=always --group-directories-first' # my preferred listing
# alias la='exa -a --color=always --group-directories-first'  # all files and dirs
# alias ll='exa -l --color=always --group-directories-first'  # long format
# alias lt='exa -aT --color=always --group-directories-first' # tree listing

alias ls='exa --group-directories-first'
alias la='ls -la --git-ignore'
alias ll='ls --tree --git-ignore'
alias laa='ls -la'
alias lla='ls --tree'
alias cll='clear && ll'
alias l.='ls -a .*'

alias nsl='nslookup'
alias cdt='pushd $(mktemp -d)'

alias dps="docker ps --format='table | {{.ID}} ~ {{.Names}} |'"
alias dpsi="docker inspect --format='| {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}} |'"
alias dpsp="docker ps --format='table | {{.ID}} ~ {{.Names}} ~ {{ .Ports }} |'"
alias dstop="docker ps -aq | xargs docker stop"

if [ $+commands[yh] ]; then
  alias dcc="docker-compose config | yh"
else
  alias dcc="docker-compose config"
fi

alias dm='docker-machine'
alias dlf='docker logs -f'

alias restart-dns-macos='sudo killall -HUP mDNSResponder;sudo killall mDNSResponderHelper;sudo dscacheutil -flushcache'

# alias ...='../..'
# alias ....='../../..'
# alias .....='../../../..'
# alias ......='../../../../..'
# alias .......='../../../../../..'
# alias ........='../../../../../../..'
#
