#!/bin/bash
if [[ "$OSTYPE" != darwin* ]]; then
  alias open='xdg-open'
  # alias xclip to pbcopy and paste
  # set pbcopy/pbpaste based on session type and available commands
  if [ -n "$XDG_SESSION_TYPE" ]; then
    case "$XDG_SESSION_TYPE" in
      wayland)
        if (( $+commands[wl-copy] )); then
          alias pbcopy='wl-copy'
          alias pbpaste='wl-paste'
        elif (( $+commands[xclip] )); then
          alias pbcopy='xclip -selection clipboard -in'
          alias pbpaste='xclip -selection clipboard -out'
        fi
        ;;
      x11)
        if (( $+commands[xclip] )); then
          alias pbcopy='xclip -selection clipboard -in'
          alias pbpaste='xclip -selection clipboard -out'
        elif (( $+commands[wl-copy] )); then
          alias pbcopy='wl-copy'
          alias pbaste='wl-paste'
        fi
        ;;
    esac
  fi

fi

function o(){
  nohup bash -c "$(whence open) $@" >/dev/null 2>&1 & disown
}

alias pbc='pbcopy'
alias pbp='pbpaste'
alias gcurl='curl --header "Authorization: Bearer $(gcloud auth print-identity-token)"'


# Add get aliase for downloading with progress
if [ $+commands[curl] ]; then
  alias get='curl --continue-at - --location --progress-bar --remote-name --remote-time'
elif [ $+commands[wget] ]; then
  alias get='wget --continue --progress=bar --timestamping'
fi

# Serve PWD over http
if [ $+commands[python3] ]; then
  alias http-serve='python3 -m http.server'
else
  alias http-serve='python -m SimpleHTTPServer'
fi

alias lanip="ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1'"

# Alias NeoVim for Vim
if command -v nvim &> /dev/null
then
  alias vim='nvim'
fi

if command -v step-cli &> /dev/null
then
  alias -g step='step-cli'
fi

if type ifconfig >/dev/null ; then
  alias inet='ifconfig | grep "inet "'
  alias inet6='ifconfig | grep "inet6 "'
else
  alias inet='ip addr | grep "inet " | tr -s " " | cut -d " " -f3'
  alias inet6='ip addr | grep "inet6 " | tr -s " " | cut -d " " -f3'
fi
alias wanip='dig @resolver1.opendns.com ANY myip.opendns.com +short'
alias dots='pushd $DOTDIR/'
alias zdots='pushd $ZDOTDIR'
alias gs='git status'
alias gds='gd --staged'
alias lspath='echo "$PATH" | tr ":" "\n"'
alias lsfpath='echo "$FPATH" | tr ":" "\n"'


alias fce='emoji::emoji_get|pbc'

alias ls='eza --group-directories-first'
alias la='ls -la --git-ignore --git'
alias ll='ls --tree --git-ignore'
alias laa='ls -la'
alias lla='ls --tree'
alias cll='clear && ll'
alias l.='ls -a .*'

alias nsl='nslookup'
alias cdt='mkdir -p "/tmp/$USER" && pushd "/tmp/$USER"'

alias dps="docker ps --format='table | {{.ID}} ~ {{.Names}} |'"
alias dpsi="docker inspect --format='| {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}} |'"
alias dpsp="docker ps --format='table | {{.ID}} ~ {{.Names}} ~ {{ .Ports }} |'"
alias dstop="docker ps -aq | xargs docker stop"

(( ${+commands[docker-compose]} )) && dccmd='docker-compose' || dccmd='docker compose'

if [ $+commands[yh] ]; then
  alias dcc="$dccmd config | yh"
else
  alias dcc="$dccmd config"
fi

alias dm='docker-machine'
alias dlf='docker logs -f'

alias restart-dns-macos='sudo killall -HUP mDNSResponder;sudo killall mDNSResponderHelper;sudo dscacheutil -flushcache'

alias icat="kitty +kitten icat"

alias dh='dirs -v'

alias zrecomp='rm ~/.cache/.zcompdump; zi compinit'

alias assume="source assume"
