#!/bin/bash

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

export DOTDIR="$XDG_CONFIG_HOME/dotfiles"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export RIPGREP_CONFIG_PATH="$XDG_CONFIG_HOME/ripgreprc"

# export HISTORY_IGNORE="(ls|cd|pwd|exit|sudo reboot|history|cd -|cd ..)"
export HISTORY_SUBSTRING_SEARCH_PREFIXED='yes'


export ZSH_CACHE_DIR="$XDG_CACHE_HOME/zsh"

export GNUPGHOME="$XDG_CONFIG_HOME/gnupg"
export GPG_TTY="$(tty)"

export STEPPATH="$XDG_CONFIG_HOME/step"

export TERM=xterm-256color

export EDITOR="nvim"
export VISUAL="nvim"
export DMEDITOR=$VISUAL
export LS_COLORS=$(cat $ZDOTDIR/LS_COLORS)

export FZF_DEFAULT_OPTS='--layout=reverse --border --inline-info --height=80%'
export FZF_DEFAULT_COMMAND='fd --type=file --hidden --follow --exclude=.git'

export ZSH_AUTOSUGGEST_STRATEGY=(history completion)

export COMPOSE_DOCKER_CLI_BUILD=1

export ASDF_DATA_DIR=$XDG_CONFIG_HOME/asdf

export JAVA_HOME=/usr/lib/jvm/default
export JDK_HOME=/usr/lib/jvm/default

export QT_QPA_PLATFORMTHEME=qt5ct

export KUBECONFIG=$XDG_CONFIG_HOME/kube/kube.config
export NeovideMultiGrid='true'

export SSH_AUTH_SOCK="$HOME/.1password/agent.sock"

export EMOJI_CLI_USE_EMOJI=true

export WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'

export DIRSTACKSIZE=8
export POWERLEVEL9K_TERM_SHELL_INTEGRATION=true

export DIRENV_LOG_FORMAT=
export skip_global_compinit=1

export AWS_EC2_METADATA_DISABLED=true
export AWS_EC2_METADATA_V1_DISABLED=true

export TERRAGRUNT_DOWNLOAD="$XDG_CACHE_HOME/terragrunt"
export TF_PLUGIN_CACHE_DIR="$XDG_CACHE_HOME/terraform.d/plugin-cache"
