#!/bin/bash

autoload -Uz edit-command-line
zle -N edit-command-line
bindkey "^x^e" edit-command-line

# Place cursor at the end of the line when searching history
autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
# bind up and down arrows to search history
#bindkey "^[[A" history-beginning-search-backward-end
#bindkey "^[[B" history-beginning-search-forward-end
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
bindkey '^e' autosuggest-accept
bindkey '^x' autosuggest-execute

# Bind home and end keys to start and end of line
bindkey  "^[[1~"   beginning-of-line
bindkey  "^[[4~"   end-of-line

# Enable Vi mode in ZSH
bindkey -v
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward
export KEYTIMEOUT=1
