#!/bin/bash

PATH=$HOME/.local/bin:$(find $XDG_CONFIG_HOME -mindepth 1 -maxdepth 2 -type d -name bin | tr '\n' ':' | sed 's/:*$//'):$PATH


if [[ "$OSTYPE" == darwin* ]]; then
  [ -d /usr/local/opt/coreutils/libexec/gnubin ] && PATH="/usr/local/opt/coreutils/libexec/gnubin":$PATH
fi

export PATH

. $ASDF_DATA_DIR/plugins/java/set-java-home.zsh 2>/dev/null
