#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    autocomplete_method = 'coc'
    snippet_engine = 'ultisnips'
    colorscheme = 'material'
    colorscheme_bg = 'dark'
    enable_guicolors = true
    enable_vimfiler_gitstatus = true
    windows_smartclose = 'Q'
    statusline_separator = 'arrow'
    statusline_iseparator = 'arrow'
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    bootstrap_before = 'bootstrap#before'
    bootstrap_after = 'bootstrap#after'


[[layers]]
    name = 'lsp'

[[layers]]
    name = 'shell'
    default_position = 'bottom'
    default_height = 30

[[layers]]
    name = 'lang#python'
    enable_typeinfo = true

[[layers]]
    name = 'lang#javascript'
    auto_fix = true
    enable_flow_syntax = true

[[layers]]
    name = 'lang#typescript'

[[layers]]
    name = 'lang#java'

[[layers]]
    name = 'lang#sh'

[[layers]]
    name = 'lang#go'

[[layers]]
    name = 'lang#toml'

[[layers]]
    name = 'lang#latex'

[[layers]]
  name = 'lang#markdown'
  enabled_formater = 'prettier'

[[layers]]
    name = 'colorscheme'

[[layers]]
    name = 'fzf'

[[layers]]
    name = 'git'

[[layers]]
    name = 'github'

[[layers]]
    name = 'ui'
    enable_scrollbar = true

[[custom_plugins]]
    repo = 'mxw/vim-jsx'
